import path from 'node:path';
import { generateContent } from './ai-engine.js';
import { logger } from '../utils/logger.js';
import { writeFile, ensureDir } from '../utils/file-utils.js';
import type {
  AggregatedData,
  TechnicalSpec,
  DiagramOutput,
  ModuleDoc,
  GeneratedPage,
  SidebarItem,
  SourceFile,
} from '../types.js';

/**
 * Doc Generator
 * Converts aggregated data + AI output into Markdown pages for VitePress
 */

const DOC_SYSTEM_PROMPT = `You are a technical documentation writer. Write clear, well-structured Markdown documentation.

Rules:
- Use proper Markdown formatting (headers, lists, tables, code blocks)
- Be concise but comprehensive
- Use professional tone
- Include relevant details from the provided context
- Do NOT add markdown frontmatter (---) unless instructed`;

/**
 * Generate all documentation pages
 */
export async function generateAllDocs(
  data: AggregatedData,
  specs: TechnicalSpec[],
  diagrams: DiagramOutput[],
  outputDir: string
): Promise<GeneratedPage[]> {
  const pages: GeneratedPage[] = [];
  const spinner = logger.spinner('Generating documentation pages...');

  try {
    // 1. Project Overview
    spinner.text = 'Generating project overview...';
    pages.push(await generateProjectOverview(data, specs, outputDir));

    // 2. Architecture page with diagrams
    spinner.text = 'Generating architecture documentation...';
    pages.push(generateArchitecturePage(diagrams, outputDir));

    // 3. Story pages (grouped by epic)
    if (data.jira) {
      spinner.text = 'Generating story documentation...';
      const storyPages = await generateStoryPages(data, specs, diagrams, outputDir);
      pages.push(...storyPages);
    }

    // 4. Module pages
    spinner.text = 'Generating module documentation...';
    const modulePages = await generateModulePages(data, diagrams, outputDir);
    pages.push(...modulePages);

    // 5. Generate VitePress config
    spinner.text = 'Generating VitePress configuration...';
    generateVitePressConfig(pages, data, outputDir);

    // 6. Update homepage
    spinner.text = 'Updating homepage...';
    generateHomepage(data, specs, outputDir);

    spinner.succeed(`Generated ${pages.length} documentation pages`);
    return pages;
  } catch (err) {
    spinner.fail('Documentation generation failed');
    throw err;
  }
}

/**
 * Generate the project overview page
 */
async function generateProjectOverview(
  data: AggregatedData,
  specs: TechnicalSpec[],
  outputDir: string
): Promise<GeneratedPage> {
  const storyCount = data.jira?.stories.length || 0;
  const epicCount = data.jira?.epics.length || 0;

  const context = `
Project: ${data.project.name}
Description: ${data.project.description || 'N/A'}
Type: ${data.local?.type || 'Unknown'}
Dependencies: ${data.local ? Object.keys(data.local.dependencies).slice(0, 20).join(', ') : 'N/A'}
User Stories: ${storyCount}
Epics: ${epicCount}
Source Files: ${data.local?.sourceFiles.length || 'N/A'}
Directories: ${data.local?.directories.slice(0, 15).join(', ') || 'N/A'}
`;

  const overview = await generateContent(
    `Write a comprehensive project overview documentation page based on this information:

${context}

${data.github?.structure.readme ? `## Project README:\n${data.github.structure.readme.substring(0, 3000)}` : ''}

Include these sections:
1. **Overview** — What the project does
2. **Tech Stack** — Technologies used (from dependencies)
3. **Project Structure** — Key directories and their purpose
4. **Getting Started** — How to set up the project (based on scripts)
5. **Key Statistics** — Stories, modules, etc.`,
    {
      systemInstruction: DOC_SYSTEM_PROMPT,
      temperature: 0.4,
      maxTokens: 4096,
    }
  );

  const content = `---
title: Project Overview
description: AI-generated overview of ${data.project.name}
---

${overview}

---

> 📝 *This documentation was auto-generated by [mvdoc](https://github.com/mvdoc) on ${new Date().toLocaleDateString()}*
`;

  const filePath = path.join(outputDir, 'overview.md');
  writeFile(filePath, content);

  return {
    filePath,
    title: 'Project Overview',
    content,
    category: 'overview',
  };
}

/**
 * Generate the architecture page with all diagrams
 */
function generateArchitecturePage(
  diagrams: DiagramOutput[],
  outputDir: string
): GeneratedPage {
  const archDir = path.join(outputDir, 'architecture');
  ensureDir(archDir);

  let content = `---
title: Architecture
description: System architecture, data flows, and diagrams
---

# Architecture

This section contains auto-generated architecture diagrams and system visualizations.

`;

  for (const diagram of diagrams) {
    content += `## ${diagram.title}

${diagram.description}

\`\`\`mermaid
${diagram.mermaidSyntax}
\`\`\`

---

`;
  }

  content += `
> 📝 *Diagrams auto-generated by mvdoc using AI analysis*
`;

  const filePath = path.join(archDir, 'index.md');
  writeFile(filePath, content);

  return {
    filePath,
    title: 'Architecture',
    content,
    category: 'architecture',
  };
}

/**
 * Generate story documentation pages grouped by epic
 */
async function generateStoryPages(
  data: AggregatedData,
  specs: TechnicalSpec[],
  diagrams: DiagramOutput[],
  outputDir: string
): Promise<GeneratedPage[]> {
  const pages: GeneratedPage[] = [];
  const storiesDir = path.join(outputDir, 'stories');
  ensureDir(storiesDir);

  // Stories index page
  let indexContent = `---
title: User Stories
description: User stories and requirements from Jira
---

# User Stories

`;

  if (data.jira) {
    // Stats table
    const statusCounts: Record<string, number> = {};
    for (const story of data.jira.stories) {
      statusCounts[story.status] = (statusCounts[story.status] || 0) + 1;
    }

    indexContent += `## Status Overview\n\n| Status | Count |\n|--------|-------|\n`;
    for (const [status, count] of Object.entries(statusCounts)) {
      indexContent += `| ${status} | ${count} |\n`;
    }
    indexContent += `| **Total** | **${data.jira.stories.length}** |\n\n`;

    // Group by epic
    if (data.jira.epics.length > 0) {
      indexContent += `## By Epic\n\n`;

      for (const epic of data.jira.epics) {
        const epicSlug = epic.key.toLowerCase();
        indexContent += `### [${epic.key}] ${epic.summary}\n\n`;
        indexContent += `**Status:** ${epic.status} | **Stories:** ${epic.stories.length}\n\n`;

        if (epic.stories.length > 0) {
          indexContent += `| Key | Summary | Status | Priority |\n|-----|---------|--------|----------|\n`;
          for (const story of epic.stories) {
            indexContent += `| [${story.key}](/stories/${story.key.toLowerCase()}) | ${story.summary} | ${story.status} | ${story.priority} |\n`;
          }
          indexContent += '\n';
        }

        // Generate individual epic page
        const epicPage = generateEpicPage(epic, specs, diagrams, storiesDir);
        pages.push(epicPage);
      }
    }

    // Stories without epic
    const orphanStories = data.jira.stories.filter((s) => !s.epic);
    if (orphanStories.length > 0) {
      indexContent += `## Unassigned Stories\n\n`;
      indexContent += `| Key | Summary | Status | Priority |\n|-----|---------|--------|----------|\n`;
      for (const story of orphanStories) {
        indexContent += `| [${story.key}](/stories/${story.key.toLowerCase()}) | ${story.summary} | ${story.status} | ${story.priority} |\n`;
      }
      indexContent += '\n';
    }

    // Individual story pages
    for (const story of data.jira.stories) {
      const spec = specs.find((s) => s.storyKey === story.key);
      const storyDiagrams = diagrams.filter((d) => d.title.includes(story.key));
      const storyPage = generateStoryPage(story, spec, storyDiagrams, storiesDir);
      pages.push(storyPage);
    }
  }

  const indexPath = path.join(storiesDir, 'index.md');
  writeFile(indexPath, indexContent);
  pages.unshift({
    filePath: indexPath,
    title: 'User Stories',
    content: indexContent,
    category: 'story',
  });

  return pages;
}

/**
 * Generate a single story page
 */
function generateStoryPage(
  story: any,
  spec: TechnicalSpec | undefined,
  diagrams: DiagramOutput[],
  storiesDir: string
): GeneratedPage {
  let content = `---
title: "${story.key} — ${story.summary}"
---

# ${story.key} — ${story.summary}

| Field | Value |
|-------|-------|
| **Status** | ${story.status} |
| **Priority** | ${story.priority} |
| **Assignee** | ${story.assignee || 'Unassigned'} |
| **Epic** | ${story.epic || 'None'} |
| **Sprint** | ${story.sprint || 'Backlog'} |
| **Labels** | ${story.labels.join(', ') || 'None'} |

## Description

${story.description || '_No description provided._'}

`;

  if (story.acceptanceCriteria) {
    content += `## Acceptance Criteria\n\n${story.acceptanceCriteria}\n\n`;
  }

  if (spec) {
    content += `## Technical Specification

${spec.specification}

`;

    if (spec.dataFlow) {
      content += `### Data Flow\n\n${spec.dataFlow}\n\n`;
    }

    if (spec.dependencies.length > 0) {
      content += `### Dependencies\n\n${spec.dependencies.map((d) => `- ${d}`).join('\n')}\n\n`;
    }

    content += `### Complexity\n\n**${spec.complexity.toUpperCase()}**\n\n`;
  }

  if (diagrams.length > 0) {
    content += `## Diagrams\n\n`;
    for (const diagram of diagrams) {
      content += `### ${diagram.title}\n\n\`\`\`mermaid\n${diagram.mermaidSyntax}\n\`\`\`\n\n`;
    }
  }

  if (story.subtasks.length > 0) {
    content += `## Subtasks\n\n| Key | Summary | Status |\n|-----|---------|--------|\n`;
    for (const st of story.subtasks) {
      content += `| ${st.key} | ${st.summary} | ${st.status} |\n`;
    }
    content += '\n';
  }

  const filePath = path.join(storiesDir, `${story.key.toLowerCase()}.md`);
  writeFile(filePath, content);

  return {
    filePath,
    title: `${story.key} — ${story.summary}`,
    content,
    category: 'story',
  };
}

/**
 * Generate an epic page
 */
function generateEpicPage(
  epic: any,
  specs: TechnicalSpec[],
  diagrams: DiagramOutput[],
  storiesDir: string
): GeneratedPage {
  let content = `---
title: "Epic: ${epic.summary}"
---

# ${epic.key} — ${epic.summary}

**Status:** ${epic.status}

## Description

${epic.description || '_No description provided._'}

## Stories (${epic.stories.length})

| Key | Summary | Status | Priority | Complexity |
|-----|---------|--------|----------|------------|
`;

  for (const story of epic.stories) {
    const spec = specs.find((s) => s.storyKey === story.key);
    content += `| [${story.key}](/stories/${story.key.toLowerCase()}) | ${story.summary} | ${story.status} | ${story.priority} | ${spec?.complexity || 'N/A'} |\n`;
  }

  const filePath = path.join(storiesDir, `epic-${epic.key.toLowerCase()}.md`);
  writeFile(filePath, content);

  return {
    filePath,
    title: `Epic: ${epic.summary}`,
    content,
    category: 'story',
  };
}

/**
 * Generate module documentation pages
 */
async function generateModulePages(
  data: AggregatedData,
  diagrams: DiagramOutput[],
  outputDir: string
): Promise<GeneratedPage[]> {
  const pages: GeneratedPage[] = [];
  const modulesDir = path.join(outputDir, 'modules');
  ensureDir(modulesDir);

  const sourceFiles = data.local?.sourceFiles || [];
  if (sourceFiles.length === 0) {
    return pages;
  }

  // Group files by top-level directory
  const moduleGroups = groupFilesByModule(sourceFiles);

  // Modules index page
  let indexContent = `---
title: Modules
description: Codebase modules and components
---

# Modules

| Module | Files | Description |
|--------|-------|-------------|
`;

  for (const [moduleName, files] of moduleGroups) {
    indexContent += `| [${moduleName}](/modules/${slugify(moduleName)}) | ${files.length} | Auto-analyzed module |\n`;

    // Generate individual module page
    const modulePage = await generateModulePage(moduleName, files, diagrams, modulesDir);
    pages.push(modulePage);
  }

  const indexPath = path.join(modulesDir, 'index.md');
  writeFile(indexPath, indexContent);
  pages.unshift({
    filePath: indexPath,
    title: 'Modules',
    content: indexContent,
    category: 'module',
  });

  return pages;
}

/**
 * Generate a single module documentation page
 */
async function generateModulePage(
  moduleName: string,
  files: SourceFile[],
  diagrams: DiagramOutput[],
  modulesDir: string
): Promise<GeneratedPage> {
  const filesList = files.map((f) => `- \`${f.relativePath}\` (${f.language})`).join('\n');

  // Let AI analyze the module
  const codeContext = files
    .slice(0, 8)
    .map((f) => `### ${f.relativePath}\n\`\`\`${f.language}\n${f.content.substring(0, 800)}\n\`\`\``)
    .join('\n\n');

  let moduleDescription = '';
  try {
    moduleDescription = await generateContent(
      `Analyze this code module "${moduleName}" and write a documentation page.

## Files
${filesList}

## Code
${codeContext}

Write these sections:
1. **Overview** — What this module does
2. **Key Components** — Main classes/functions/components
3. **Data Flow** — How data moves through this module
4. **Dependencies** — What this module depends on
5. **Public API** — Exported functions/components and their purpose`,
      {
        systemInstruction: DOC_SYSTEM_PROMPT,
        temperature: 0.3,
        maxTokens: 3072,
      }
    );
  } catch {
    moduleDescription = `This module contains ${files.length} files.\n\n## Files\n\n${filesList}`;
  }

  // Find related diagrams
  const moduleDiagrams = diagrams.filter((d) =>
    d.title.toLowerCase().includes(moduleName.toLowerCase())
  );

  let content = `---
title: "${moduleName}"
---

# ${moduleName}

${moduleDescription}

## File Structure

${filesList}
`;

  if (moduleDiagrams.length > 0) {
    content += `\n## Diagrams\n\n`;
    for (const d of moduleDiagrams) {
      content += `### ${d.title}\n\n\`\`\`mermaid\n${d.mermaidSyntax}\n\`\`\`\n\n`;
    }
  }

  const filePath = path.join(modulesDir, `${slugify(moduleName)}.md`);
  writeFile(filePath, content);

  return {
    filePath,
    title: moduleName,
    content,
    category: 'module',
  };
}

/**
 * Generate VitePress config file
 */
function generateVitePressConfig(
  pages: GeneratedPage[],
  data: AggregatedData,
  outputDir: string
): void {
  const sidebar = buildSidebar(pages, outputDir);

  const config = `import { defineConfig } from 'vitepress';

export default defineConfig({
  title: '${data.project.name}',
  description: '${data.project.description || 'AI-Generated Documentation'}',
  
  themeConfig: {
    logo: '/logo.svg',
    
    nav: [
      { text: 'Overview', link: '/overview' },
      { text: 'Architecture', link: '/architecture/' },
      { text: 'Stories', link: '/stories/' },
      { text: 'Modules', link: '/modules/' },
    ],

    sidebar: ${JSON.stringify(sidebar, null, 6)},

    socialLinks: [
      ${data.github ? `{ icon: 'github', link: 'https://github.com/${data.github.structure.owner}/${data.github.structure.repo}' },` : ''}
    ],

    search: {
      provider: 'local',
    },

    footer: {
      message: 'Generated by mvdoc — AI-Powered Documentation',
      copyright: \`Last generated: \${new Date().toLocaleDateString()}\`,
    },
  },

  markdown: {
    // Enable Mermaid diagrams
    config: (md) => {
      // Mermaid support is built-in in VitePress 1.x
    },
  },

  mermaid: {},
});
`;

  const configDir = path.join(outputDir, '.vitepress');
  ensureDir(configDir);
  writeFile(path.join(configDir, 'config.mts'), config);
}

/**
 * Generate/update homepage
 */
function generateHomepage(
  data: AggregatedData,
  specs: TechnicalSpec[],
  outputDir: string
): void {
  const storyCount = data.jira?.stories.length || 0;
  const moduleCount = data.local
    ? new Set(data.local.sourceFiles.map((f) => f.relativePath.split('/')[0])).size
    : 0;

  const content = `---
layout: home
hero:
  name: "${data.project.name}"
  text: "AI-Generated Documentation"
  tagline: "${data.project.description || 'Auto-generated from Jira stories, GitHub code, and AI analysis'}"
  actions:
    - theme: brand
      text: Project Overview →
      link: /overview
    - theme: alt
      text: Architecture
      link: /architecture/
features:
  - icon: 📋
    title: ${storyCount} User Stories
    details: Requirements and specifications from Jira, analyzed and enriched with AI.
    link: /stories/
  - icon: 🏗️
    title: ${moduleCount} Modules
    details: Codebase analysis with data flows, dependencies, and architecture diagrams.
    link: /modules/
  - icon: 📊
    title: Auto-Generated Diagrams
    details: Flowcharts, sequence diagrams, ER diagrams, and architecture views.
    link: /architecture/
  - icon: 💬
    title: Ask Your Docs
    details: AI-powered chat to answer questions about this project.
---
`;

  writeFile(path.join(outputDir, 'index.md'), content);
}

// ─── Helpers ───

function groupFilesByModule(files: SourceFile[]): Map<string, SourceFile[]> {
  const groups = new Map<string, SourceFile[]>();

  for (const file of files) {
    const parts = file.relativePath.split('/');
    // Use the first directory as module name, or 'root' for top-level files
    const moduleName = parts.length > 1 ? parts[0] : 'root';

    if (!groups.has(moduleName)) {
      groups.set(moduleName, []);
    }
    groups.get(moduleName)!.push(file);
  }

  return groups;
}

function buildSidebar(pages: GeneratedPage[], outputDir: string): SidebarItem[] {
  const sidebar: SidebarItem[] = [];

  // Overview
  sidebar.push({ text: 'Project Overview', link: '/overview' });

  // Architecture
  const archPages = pages.filter((p) => p.category === 'architecture');
  if (archPages.length > 0) {
    sidebar.push({
      text: 'Architecture',
      link: '/architecture/',
      collapsed: false,
    });
  }

  // Stories
  const storyPages = pages.filter((p) => p.category === 'story');
  if (storyPages.length > 0) {
    sidebar.push({
      text: 'User Stories',
      link: '/stories/',
      collapsed: true,
      items: storyPages
        .filter((p) => !p.filePath.endsWith('index.md'))
        .slice(0, 30) // Limit sidebar items
        .map((p) => ({
          text: p.title,
          link: '/' + path.relative(outputDir, p.filePath).replace(/\.md$/, ''),
        })),
    });
  }

  // Modules
  const modulePages = pages.filter((p) => p.category === 'module');
  if (modulePages.length > 0) {
    sidebar.push({
      text: 'Modules',
      link: '/modules/',
      collapsed: true,
      items: modulePages
        .filter((p) => !p.filePath.endsWith('index.md'))
        .map((p) => ({
          text: p.title,
          link: '/' + path.relative(outputDir, p.filePath).replace(/\.md$/, ''),
        })),
    });
  }

  return sidebar;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}
